In [2]:
import pandas as pd
import numpy as np

In [3]:
date=pd.read_csv('date data set.csv')
time=pd.read_csv('time dataset (2).csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-10-17        2824        2     190
1  2018-10-09        5012       15      36
2  2018-04-15        9935        6     152
3  2019-03-09        1520        2      24
4  2018-08-12        4811       33     155

In [5]:
time.head()

                  date                                             msg
0  2012-04-17 01:17:05   Ищу девушку до 40 лет для серьезных отношений
1  2014-04-14 13:17:06  Спасибо за вчерашний вечер, было очень приятно
2  2012-03-19 01:24:34                М 38, Киев, знакомства и общение
3  2013-11-11 17:21:21  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС СМС ММС 0955532826
4  2012-11-22 01:10:08                М 38, Киев, знакомства и общение

In [6]:
# by default the date and time in pyhthon is object so first we convert it in to converable data type

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        200 non-null    object
 1   product_id  200 non-null    int64
 2   city_id     200 non-null    int64
 3   orders      200 non-null    int64
dtypes: int64(3), object(1)
memory usage: 6.4+ KB

In [8]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    200 non-null    object
 1   msg     200 non-null    object
dtypes: object(2)
memory usage: 3.3+ KB

In [9]:
#now we convert the date col to time and date datatype

In [10]:
date['date']=pd.to_datetime(date['date'])

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        200 non-null    datetime64[ns]
 1   product_id  200 non-null    int64
 2   city_id     200 non-null    int64
 3   orders      200 non-null    int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 6.4 KB

In [12]:
# now we extract thing one by one

In [13]:
date['date_year']=date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-10-17        2824        2     190       2019
1 2018-10-09        5012       15      36       2018
2 2018-04-15        9935        6     152       2018
3 2019-03-09        1520        2      24       2019
4 2018-08-12        4811       33     155       2018

In [14]:
# if we want the name of month or only month
date['month']=date['date'].dt.month

In [15]:
date.sample()

        date  product_id  city_id  orders  date_year  month
1 2018-10-09        5012       15      36       2018     10

In [16]:
# if want name

date['month']=date['date'].dt.month_name()

In [17]:
date.sample(6)

          date  product_id  city_id  orders  date_year     month
150 2019-07-25        5082        8     117       2019      July
181 2018-02-11        1508       16      52       2018  February
94  2019-12-22        5956       40     168       2019  December
11  2019-01-03        6635       39      68       2019   January
33  2018-04-23        3504       41      41       2018     April
147 2018-06-01        1090       49     198       2018      June

In [18]:
# if we want the name of month or only month
date['day']=date['date'].dt.day

In [19]:
date.sample(7)

          date  product_id  city_id  orders  date_year     month  day
134 2019-07-22        3085       13     108       2019      July   22
197 2019-05-11        8616       28     188       2019       May   11
19  2018-12-30        4432       43      69       2018  December   30
116 2018-04-21        7267        3     121       2018     April   21
83  2019-02-18        2964       37      64       2019  February   18
4   2018-08-12        4811       33     155       2018    August   12
76  2019-07-24        8973       10      49       2019      July   24

In [20]:
# if we want the name of month or only month
date['day_of week']=date['date'].dt.day_name()

In [21]:
date.sample(8)

,date,product_id,city_id,orders,date_year,month,day,day_of week
43,2018-06-06,7126,49,42,2018,June,6,Wednesday
63,2019-11-06,8062,23,109,2019,November,6,Wednesday
56,2019-07-22,4770,38,57,2019,July,22,Monday
28,2018-05-27,5339,9,64,2018,May,27,Sunday
72,2018-06-20,7658,32,124,2018,June,20,Wednesday
86,2018-07-29,6147,16,68,2018,July,29,Sunday
14,2019-10-06,6925,37,50,2019,October,6,Sunday
142,2018-08-29,6085,15,51,2018,August,29,Wednesday

In [22]:
#is the particular day is weekend
date['weekend_day']=np.where(date['day_of week'].isin(['Sunday','Saturday']), 1,0)
date.drop(columns=['product_id','city_id','orders'])

          date  date_year    month  day day_of week  weekend_day
0   2019-10-17       2019  October   17    Thursday            0
1   2018-10-09       2018  October    9     Tuesday            0
2   2018-04-15       2018    April   15      Sunday            1
3   2019-03-09       2019    March    9    Saturday            1
4   2018-08-12       2018   August   12      Sunday            1
..         ...        ...      ...  ...         ...          ...
195 2019-04-16       2019    April   16     Tuesday            0
196 2019-06-19       2019     June   19   Wednesday            0
197 2019-05-11       2019      May   11    Saturday            1
198 2019-08-30       2019   August   30      Friday            0
199 2018-03-30       2018    March   30      Friday            0

[200 rows x 6 columns]

In [23]:
date.sample(10)

,date,product_id,city_id,orders,date_year,month,day,day_of week,weekend_day
157,2019-06-18,8939,41,62,2019,June,18,Tuesday,0
63,2019-11-06,8062,23,109,2019,November,6,Wednesday,0
0,2019-10-17,2824,2,190,2019,October,17,Thursday,0
118,2018-11-09,4728,15,7,2018,November,9,Friday,0
42,2019-10-17,9317,39,51,2019,October,17,Thursday,0
199,2018-03-30,5569,29,63,2018,March,30,Friday,0
113,2019-02-27,1406,12,189,2019,February,27,Wednesday,0
148,2018-04-20,7965,15,46,2018,April,20,Friday,0
172,2019-09-30,9751,2,101,2019,September,30,Monday,0
43,2018-06-06,7126,49,42,2018,June,6,Wednesday,0

In [24]:
#week
date['week_of_year']=date['date'].dt.isocalendar().week

In [25]:
date.sample()

,date,product_id,city_id,orders,date_year,month,day,day_of week,weekend_day,week_of_year
198,2019-08-30,5397,21,63,2019,August,30,Friday,0,35

In [26]:
date.drop(columns=['product_id','city_id','orders','week_of month'],inplace=True)

KeyError: "['week_of month'] not found in axis"

In [ ]:
date.sample(7)

In [ ]:
# semester or quarter
date['quarter_of_year']=date['date'].dt.quarter

In [ ]:
date.head()

In [ ]:
# semester
date['semester_of_year']=np.where(date['quarter_of_year'].isin([1,2]), 1,2)

In [27]:
date.head()

,date,product_id,city_id,orders,date_year,month,day,day_of week,weekend_day,week_of_year
0,2019-10-17,2824,2,190,2019,October,17,Thursday,0,42
1,2018-10-09,5012,15,36,2018,October,9,Tuesday,0,41
2,2018-04-15,9935,6,152,2018,April,15,Sunday,1,15
3,2019-03-09,1520,2,24,2019,March,9,Saturday,1,10
4,2018-08-12,4811,33,155,2018,August,12,Sunday,1,32

In [28]:
# if want to find gape b/w time
import datetime
today=datetime.datetime.today()
today

datetime.datetime(2026, 8, 10, 17, 4, 10, 305548)

In [29]:
today- date['date']         # show diff b/w that time and now time

0     2489 days 17:04:10.305548
1     2862 days 17:04:10.305548
2     3039 days 17:04:10.305548
3     2711 days 17:04:10.305548
4     2920 days 17:04:10.305548
                 ...
195   2673 days 17:04:10.305548
196   2609 days 17:04:10.305548
197   2648 days 17:04:10.305548
198   2537 days 17:04:10.305548
199   3055 days 17:04:10.305548
Name: date, Length: 200, dtype: timedelta64[ns]

In [30]:
(today- date['date']).dt.days

0      2489
1      2862
2      3039
3      2711
4      2920
       ...
195    2673
196    2609
197    2648
198    2537
199    3055
Name: date, Length: 200, dtype: int64

In [31]:
#month pass
np.round((today - date['date']) / np.timedelta64(30, 'D'), 0)

0       83.0
1       95.0
2      101.0
3       90.0
4       97.0
       ...
195     89.0
196     87.0
197     88.0
198     85.0
199    102.0
Name: date, Length: 200, dtype: float64

In [32]:
#time

In [33]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    200 non-null    object
 1   msg     200 non-null    object
dtypes: object(2)
memory usage: 3.3+ KB

In [34]:
time['date']=pd.to_datetime(time['date'])

In [35]:
time

                   date                                                msg
0   2012-04-17 01:17:05      Ищу девушку до 40 лет для серьезных отношений
1   2014-04-14 13:17:06     Спасибо за вчерашний вечер, было очень приятно
2   2012-03-19 01:24:34                   М 38, Киев, знакомства и общение
3   2013-11-11 17:21:21     ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС СМС ММС 0955532826
4   2012-11-22 01:10:08                   М 38, Киев, знакомства и общение
..                  ...                                                ...
195 2013-01-08 05:26:08                Ищу компанию на вечер, пишите в смс
196 2014-05-27 15:08:54  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
197 2012-06-27 00:10:50       Зая я тебя никогда не обижу люблю тебя! Даше
198 2012-10-05 02:21:02                   Сегодня вечером буду дома, звони
199 2013-09-10 03:09:14          Киев. мужчина 40, познакомлюсь с девушкой

[200 rows x 2 columns]

In [36]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    200 non-null    datetime64[ns]
 1   msg     200 non-null    object
dtypes: datetime64[ns](1), object(1)
memory usage: 3.3+ KB

In [37]:
time['hours']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second

In [38]:
time.sample(5)

,date,msg,hours,min,sec
98,2013-02-09 15:31:46,"Напиши свой номер телефона, пожалуйста",15,31,46
175,2012-06-20 10:13:32,Позвони мне когда будешь свободен 0671234567,10,13,32
1,2014-04-14 13:17:06,"Спасибо за вчерашний вечер, было очень приятно",13,17,6
180,2013-01-20 12:35:12,Ищу новых друзей для общения,12,35,12
169,2012-07-10 20:20:35,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,20,20,35